name: Build And Test

on:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: build-${{ github.head_ref || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: treeform/setup-nim-action@v6
      - run: nimby sync -g nimby.lock
      - run: make test
      - run: make build
